#! /bin/zsh

NORMAL="\e[1;0m"
GREEN="\e[1;32m"

# require one argument
[ -z $1 ] && echo "no arguments provided" && exit
[ $2 ] && echo "too many arguments provided" && exit

echo "creating ${GREEN}blog/$1.mdx${NORMAL}..."

d=$(date '+%Y-%m-%d')
cat << EOF > blog/$1.mdx
---
title: 'title'
publishedAt: '$d'
summary: 'summary'
tags: [untagged]
---

gud stuff.
EOF
echo "done."
nvim blog/$1.mdx
